import = [
  "~/.config/alacritty/alacritty-theme/themes/xterm.toml"
]

[env]
TERM = "xterm-256color"

[window]
padding = { x = 10, y = 10 }

decorations = "Buttonless"

option_as_alt = "Both"

[font]
normal.family = "MesloLGS Nerd Font Mono"

size = 18
